### ISSUE TITLE
GetUserScoresAsync throws System.InvalidOperationException

### ISSUE THREAD

**Issue by swyrin** [Kiritsu/OsuSharp#13]
### Expected result
The method will return a list of `IUser`

### Actual result
It throws "System.InvalidOperationException: Sequence contains no matching element" instead.

The request seems to work when I log at Verbose level, but I don't know what happened then.

### Code to reproduce
```csharp
try
{
    IUser user = await _client.GetUserAsync("sakamata1");
    IReadOnlyList<IScore> bestScores = await _client.GetUserScoresAsync(user.Id, ScoreType.Firsts, limit: 10);
}
catch (InvalidOperationException _)
{
   // exception thrown
}
```

### Additional Stuffs
- I am using the latest OsuSharp version at SlimGet
- Stack trace:
```
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at OsuSharp.Mapper.OsuSharpMapper.Transform[TImplementation,TModel](TModel model, IOsuClient client)
   at OsuSharp.Net.DefaultRequestHandler.SendAsync[TImplementation,TModel](IOsuApiRequest request, CancellationToken token)
   at OsuSharp.OsuClient.GetUserScoresAsync(Int64 userId, ScoreType type, Boolean includeFails, Nullable`1 gameMode, Nullable`1 limit, Nullable`1 offset, CancellationToken token)
   ```

**Comment by Kiritsu** [comment]
Looks like I broke the auto mapper with arrays of models... I'll check ASAP

**Comment by Kiritsu** [comment]
CI is running, should be fixed in next nightly version

**Comment by swyrin** [comment]
glad to hear that

**Comment by swyrin** [comment]
the mentioned issue is fixed now, thank you.
